version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/Chifez/gitai/cmd.Version={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: Chifez
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/Chifez/gitai
    description: AI-powered git commit CLI
    license: MIT

scoops:
  - repository:
      owner: Chifez
      name: scoop-bucket
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/Chifez/gitai
    description: AI-powered git commit CLI
    license: MIT
